/* Lisan — the Spanish course.
 *
 * Latin American Spanish, which is what most English speakers will actually
 * hear and use. Where Castilian differs in a way that matters — the "th" for
 * c/z, vosotros — it is called out in a note rather than taught separately.
 *
 * Nouns are always introduced with their article, because "mesa" without "la"
 * is half a word: the gender has to be learned at the same time as the noun or
 * it never gets learned at all.
 */
(function () {
'use strict';

var SPANISH = {
  id: 'es',
  name: 'Spanish',
  native: 'Español',
  dir: 'ltr',
  script: 'latin',
  speech: ['es-MX', 'es-US', 'es-419', 'es-ES', 'es'],
  gendered: true,
  order: 3,
  blurb: 'Latin American Spanish — the most widely spoken second language in the Americas.',
  grammar: {
    wordOrder: 'Spanish puts the adjective after the noun (la casa grande, "the house big") ' +
               'and lets you drop the subject pronoun, because the verb ending already says who.',
    articles: { m: 'el', f: 'la' },
    genderNote: 'Nouns ending in -o are usually masculine (el libro); -a is usually feminine ' +
                '(la mesa). The exceptions worth knowing early: el día, el mapa, la mano, el problema.'
  },
  units: [

  { id: 'es-greet', kind: 'words', title: 'Greetings',
    blurb: 'Enough to open and close a conversation politely.',
    vocab: [
      { t: 'hola', e: 'hello' },
      { t: 'buenos días', e: 'good morning', n: 'Literally "good days". Used until about midday.' },
      { t: 'buenas tardes', e: 'good afternoon' },
      { t: 'buenas noches', e: 'good evening' },
      { t: 'adiós', e: 'goodbye' },
      { t: 'hasta luego', e: 'see you later', n: 'Far more common in daily life than adiós, which can sound final.' },
      { t: 'gracias', e: 'thank you' },
      { t: 'de nada', e: 'you are welcome' },
      { t: 'por favor', e: 'please' },
      { t: 'perdón', e: 'sorry' },
      { t: 'sí', e: 'yes' },
      { t: 'no', e: 'no' },
      { t: 'bien', e: 'well' },
      { t: 'mal', e: 'badly' },
      { t: 'mucho gusto', e: 'pleased to meet you' },
      { t: 'lo siento', e: 'I am sorry' },
      { t: 'claro', e: 'of course' },
      { t: 'también', e: 'also' }
    ],
    sentences: [
      { t: '¿ Cómo estás ?', e: 'how are you ?' },
      { t: 'Estoy bien , gracias', e: 'I am well , thank you' },
      { t: '¿ Cómo te llamas ?', e: 'what is your name ?', n: 'Literally "how do you call yourself?"' },
      { t: 'Me llamo Ana', e: 'my name is Ana' },
      { t: 'Mucho gusto , Ana', e: 'pleased to meet you , Ana' },
      { t: 'Buenos días , señor', e: 'good morning , sir' },
      { t: 'Hasta luego , amigo', e: 'see you later , friend' },
      { t: 'Muchas gracias por todo', e: 'thank you very much for everything' }
    ] },

  { id: 'es-people', kind: 'words', title: 'People',
    blurb: 'Pronouns, and the words for who you are talking about.',
    vocab: [
      { t: 'yo', e: 'I' },
      { t: 'tú', e: 'you', n: 'Informal. Use usted with strangers, older people and anyone senior to you.' },
      { t: 'usted', e: 'you formal' },
      { t: 'él', e: 'he' },
      { t: 'ella', e: 'she' },
      { t: 'nosotros', e: 'we' },
      { t: 'ellos', e: 'they' },
      { t: 'el hombre', e: 'the man', g: 'm' },
      { t: 'la mujer', e: 'the woman', g: 'f' },
      { t: 'el niño', e: 'the boy', g: 'm' },
      { t: 'la niña', e: 'the girl', g: 'f' },
      { t: 'el amigo', e: 'the friend', g: 'm' },
      { t: 'la persona', e: 'the person', g: 'f', n: 'Always feminine, even for a man: él es una persona buena.' },
      { t: 'la gente', e: 'the people', g: 'f', n: 'Singular in Spanish — la gente es, not son.' },
      { t: 'el señor', e: 'the gentleman', g: 'm' },
      { t: 'la señora', e: 'the lady', g: 'f' },
      { t: 'el vecino', e: 'the neighbour', g: 'm' },
      { t: 'el nombre', e: 'the name', g: 'm' }
    ],
    sentences: [
      { t: 'Yo soy estudiante', e: 'I am a student', n: 'Spanish drops "a" before a job or role: soy estudiante, not soy un estudiante.' },
      { t: 'Ella es mi amiga', e: 'she is my friend' },
      { t: 'Él es un hombre bueno', e: 'he is a good man' },
      { t: 'Nosotros somos amigos', e: 'we are friends' },
      { t: '¿ Quién es esa mujer ?', e: 'who is that woman ?' },
      { t: 'La gente aquí es amable', e: 'the people here are kind' },
      { t: 'Mi vecino habla español', e: 'my neighbour speaks Spanish' }
    ] },

  { id: 'es-ser', kind: 'words', title: 'To be: ser and estar',
    blurb: 'Spanish has two verbs for "to be". This is the thing to get right early.',
    vocab: [
      { t: 'soy', e: 'I am', n: 'From ser — for what something permanently is: soy canadiense.' },
      { t: 'eres', e: 'you are' },
      { t: 'es', e: 'he is' },
      { t: 'somos', e: 'we are' },
      { t: 'son', e: 'they are' },
      { t: 'estoy', e: 'I am located', n: 'From estar — for where you are and how you feel right now: estoy en casa, estoy cansado.' },
      { t: 'estás', e: 'you are located' },
      { t: 'está', e: 'he is located' },
      { t: 'estamos', e: 'we are located' },
      { t: 'están', e: 'they are located' },
      { t: 'canadiense', e: 'Canadian' },
      { t: 'mexicano', e: 'Mexican' },
      { t: 'el profesor', e: 'the teacher', g: 'm' },
      { t: 'el estudiante', e: 'the student', g: 'm' },
      { t: 'el médico', e: 'the doctor', g: 'm' },
      { t: 'cansado', e: 'tired' },
      { t: 'ocupado', e: 'busy' },
      { t: 'listo', e: 'ready', n: 'With estar it means ready; with ser it means clever. Same word, two meanings.' }
    ],
    sentences: [
      { t: 'Soy canadiense', e: 'I am Canadian' },
      { t: 'Estoy cansado hoy', e: 'I am tired today' },
      { t: 'Ella es profesora', e: 'she is a teacher' },
      { t: '¿ Dónde estás ?', e: 'where are you ?' },
      { t: 'Estamos en casa', e: 'we are at home' },
      { t: 'El café está frío', e: 'the coffee is cold', n: 'Estar, because it is cold right now. Ser would mean coffee is a cold thing by nature.' },
      { t: 'Mi hermano es médico', e: 'my brother is a doctor' },
      { t: 'Estoy muy ocupado', e: 'I am very busy' }
    ] },

  { id: 'es-family', kind: 'words', title: 'Family',
    blurb: 'The people you talk about most.',
    vocab: [
      { t: 'la familia', e: 'the family', g: 'f' },
      { t: 'el padre', e: 'the father', g: 'm' },
      { t: 'la madre', e: 'the mother', g: 'f' },
      { t: 'el hermano', e: 'the brother', g: 'm' },
      { t: 'la hermana', e: 'the sister', g: 'f' },
      { t: 'el hijo', e: 'the son', g: 'm' },
      { t: 'la hija', e: 'the daughter', g: 'f' },
      { t: 'el abuelo', e: 'the grandfather', g: 'm' },
      { t: 'la abuela', e: 'the grandmother', g: 'f' },
      { t: 'el esposo', e: 'the husband', g: 'm' },
      { t: 'la esposa', e: 'the wife', g: 'f' },
      { t: 'el tío', e: 'the uncle', g: 'm' },
      { t: 'el primo', e: 'the cousin', g: 'm' },
      { t: 'los padres', e: 'the parents', n: 'The masculine plural covers a mixed group — los padres is both parents, not two fathers.' },
      { t: 'mi', e: 'my' },
      { t: 'tu', e: 'your' },
      { t: 'su', e: 'his' },
      { t: 'nuestro', e: 'our' }
    ],
    sentences: [
      { t: 'Tengo dos hermanas', e: 'I have two sisters' },
      { t: 'Mi madre se llama Elena', e: 'my mother is called Elena' },
      { t: '¿ Tienes hermanos ?', e: 'do you have siblings ?' },
      { t: 'Mi familia vive en México', e: 'my family lives in Mexico' },
      { t: 'Su padre trabaja aquí', e: 'his father works here' },
      { t: 'Nuestra abuela tiene ochenta años', e: 'our grandmother is eighty years old', n: 'Spanish says you *have* years: tiene ochenta años.' },
      { t: 'Ella es mi hija', e: 'she is my daughter' }
    ] },

  { id: 'es-num', kind: 'words', title: 'Numbers',
    blurb: 'One to a hundred, and how to count things.',
    vocab: [
      { t: 'uno', e: 'one' },
      { t: 'dos', e: 'two' },
      { t: 'tres', e: 'three' },
      { t: 'cuatro', e: 'four' },
      { t: 'cinco', e: 'five' },
      { t: 'seis', e: 'six' },
      { t: 'siete', e: 'seven' },
      { t: 'ocho', e: 'eight' },
      { t: 'nueve', e: 'nine' },
      { t: 'diez', e: 'ten' },
      { t: 'once', e: 'eleven' },
      { t: 'doce', e: 'twelve' },
      { t: 'veinte', e: 'twenty' },
      { t: 'treinta', e: 'thirty' },
      { t: 'cincuenta', e: 'fifty' },
      { t: 'cien', e: 'one hundred' },
      { t: 'mil', e: 'one thousand' },
      { t: 'primero', e: 'first' },
      { t: 'mucho', e: 'a lot' },
      { t: 'poco', e: 'a little' }
    ],
    sentences: [
      { t: 'Tengo veinte años', e: 'I am twenty years old' },
      { t: 'Cuesta cinco dólares', e: 'it costs five dollars' },
      { t: '¿ Cuántos años tienes ?', e: 'how old are you ?' },
      { t: 'Hay tres personas aquí', e: 'there are three people here', n: 'Hay is "there is" and "there are" — one word for both.' },
      { t: 'Quiero dos , por favor', e: 'I want two , please' },
      { t: 'Son las diez', e: 'it is ten o\'clock' }
    ] },

  { id: 'es-food', kind: 'words', title: 'Food and drink',
    blurb: 'Ordering, and saying what you like.',
    vocab: [
      { t: 'el agua', e: 'the water', g: 'f', n: 'Feminine, but takes el because agua starts with a stressed a. You still say el agua fría.' },
      { t: 'el pan', e: 'the bread', g: 'm' },
      { t: 'el arroz', e: 'the rice', g: 'm' },
      { t: 'la carne', e: 'the meat', g: 'f' },
      { t: 'el pollo', e: 'the chicken', g: 'm' },
      { t: 'el pescado', e: 'the fish', g: 'm' },
      { t: 'el huevo', e: 'the egg', g: 'm' },
      { t: 'la leche', e: 'the milk', g: 'f' },
      { t: 'el café', e: 'the coffee', g: 'm' },
      { t: 'el té', e: 'the tea', g: 'm' },
      { t: 'el jugo', e: 'the juice', g: 'm' },
      { t: 'la manzana', e: 'the apple', g: 'f' },
      { t: 'el queso', e: 'the cheese', g: 'm' },
      { t: 'la sal', e: 'the salt', g: 'f' },
      { t: 'la comida', e: 'the food', g: 'f' },
      { t: 'el restaurante', e: 'the restaurant', g: 'm' },
      { t: 'la cuenta', e: 'the bill', g: 'f' },
      { t: 'comer', e: 'to eat' },
      { t: 'beber', e: 'to drink' },
      { t: 'delicioso', e: 'delicious' }
    ],
    sentences: [
      { t: 'Quiero un café , por favor', e: 'I want a coffee , please' },
      { t: 'El pan está delicioso', e: 'the bread is delicious' },
      { t: 'No como carne', e: 'I do not eat meat' },
      { t: 'La cuenta , por favor', e: 'the bill , please' },
      { t: '¿ Qué quieres comer ?', e: 'what do you want to eat ?' },
      { t: 'Bebo café por la mañana', e: 'I drink coffee in the morning' },
      { t: 'Me gusta el pescado', e: 'I like fish', n: 'Literally "fish pleases me". The thing liked is the subject, so it is me gusta el libro but me gustan los libros.' }
    ] },

  { id: 'es-places', kind: 'words', title: 'Places',
    blurb: 'Where things are, and how to ask.',
    vocab: [
      { t: 'la casa', e: 'the house', g: 'f' },
      { t: 'la escuela', e: 'the school', g: 'f' },
      { t: 'el mercado', e: 'the market', g: 'm' },
      { t: 'la ciudad', e: 'the city', g: 'f' },
      { t: 'la calle', e: 'the street', g: 'f' },
      { t: 'el hotel', e: 'the hotel', g: 'm' },
      { t: 'el hospital', e: 'the hospital', g: 'm' },
      { t: 'la oficina', e: 'the office', g: 'f' },
      { t: 'la tienda', e: 'the shop', g: 'f' },
      { t: 'el baño', e: 'the bathroom', g: 'm' },
      { t: 'aquí', e: 'here' },
      { t: 'allí', e: 'there' },
      { t: 'cerca', e: 'near' },
      { t: 'lejos', e: 'far' },
      { t: 'a la derecha', e: 'to the right' },
      { t: 'a la izquierda', e: 'to the left' },
      { t: 'en', e: 'in' },
      { t: 'con', e: 'with' }
    ],
    sentences: [
      { t: '¿ Dónde está el baño ?', e: 'where is the bathroom ?' },
      { t: 'El mercado está cerca', e: 'the market is near' },
      { t: 'Vivo en una ciudad grande', e: 'I live in a big city' },
      { t: 'La tienda está a la derecha', e: 'the shop is to the right' },
      { t: 'Voy a la escuela', e: 'I go to the school' },
      { t: '¿ Está lejos de aquí ?', e: 'is it far from here ?' },
      { t: 'Mi casa está en esa calle', e: 'my house is on that street' }
    ] },

  { id: 'es-verbs', kind: 'words', title: 'Everyday verbs',
    blurb: 'The present tense, and the endings that carry it.',
    vocab: [
      { t: 'hablar', e: 'to speak', n: 'An -ar verb: hablo, hablas, habla, hablamos, hablan.' },
      { t: 'hablo', e: 'I speak' },
      { t: 'leer', e: 'to read', n: 'An -er verb: leo, lees, lee, leemos, leen.' },
      { t: 'leo', e: 'I read' },
      { t: 'vivir', e: 'to live', n: 'An -ir verb: vivo, vives, vive, vivimos, viven.' },
      { t: 'vivo', e: 'I live' },
      { t: 'tener', e: 'to have' },
      { t: 'tengo', e: 'I have' },
      { t: 'querer', e: 'to want' },
      { t: 'quiero', e: 'I want' },
      { t: 'ir', e: 'to go' },
      { t: 'voy', e: 'I go' },
      { t: 'hacer', e: 'to do' },
      { t: 'hago', e: 'I do' },
      { t: 'saber', e: 'to know' },
      { t: 'sé', e: 'I know' },
      { t: 'trabajar', e: 'to work' },
      { t: 'trabajo', e: 'I work' },
      { t: 'entender', e: 'to understand' },
      { t: 'necesitar', e: 'to need' }
    ],
    sentences: [
      { t: 'Hablo un poco de español', e: 'I speak a little Spanish' },
      { t: 'No entiendo', e: 'I do not understand', n: 'No goes straight before the verb. There is no extra word for "do".' },
      { t: '¿ Hablas inglés ?', e: 'do you speak English ?' },
      { t: 'Trabajo en una oficina', e: 'I work in an office' },
      { t: 'Necesito ayuda', e: 'I need help' },
      { t: 'Quiero aprender español', e: 'I want to learn Spanish' },
      { t: 'Vivimos en Canadá', e: 'we live in Canada' },
      { t: '¿ Qué haces ?', e: 'what are you doing ?' }
    ] },

  { id: 'es-desc', kind: 'words', title: 'Describing things',
    blurb: 'Adjectives, and making them agree.',
    vocab: [
      { t: 'grande', e: 'big' },
      { t: 'pequeño', e: 'small' },
      { t: 'nuevo', e: 'new' },
      { t: 'viejo', e: 'old' },
      { t: 'bueno', e: 'good' },
      { t: 'malo', e: 'bad' },
      { t: 'bonito', e: 'pretty' },
      { t: 'feo', e: 'ugly' },
      { t: 'caro', e: 'expensive' },
      { t: 'barato', e: 'cheap' },
      { t: 'fácil', e: 'easy' },
      { t: 'difícil', e: 'difficult' },
      { t: 'rápido', e: 'fast' },
      { t: 'lento', e: 'slow' },
      { t: 'caliente', e: 'hot' },
      { t: 'frío', e: 'cold' },
      { t: 'largo', e: 'long' },
      { t: 'corto', e: 'short' },
      { t: 'muy', e: 'very' },
      { t: 'más', e: 'more' }
    ],
    sentences: [
      { t: 'La casa es muy grande', e: 'the house is very big' },
      { t: 'Es un libro nuevo', e: 'it is a new book' },
      { t: 'Las manzanas son baratas', e: 'the apples are cheap', n: 'The adjective agrees in both gender and number: barato, barata, baratos, baratas.' },
      { t: 'El español no es difícil', e: 'Spanish is not difficult' },
      { t: 'Mi coche es viejo', e: 'my car is old' },
      { t: 'Este café está caliente', e: 'this coffee is hot' },
      { t: 'Quiero algo más barato', e: 'I want something cheaper' }
    ] },

  { id: 'es-quest', kind: 'words', title: 'Questions',
    blurb: 'The question words, all of which carry an accent.',
    vocab: [
      { t: 'qué', e: 'what' },
      { t: 'quién', e: 'who' },
      { t: 'dónde', e: 'where' },
      { t: 'cuándo', e: 'when' },
      { t: 'por qué', e: 'why' },
      { t: 'cómo', e: 'how' },
      { t: 'cuánto', e: 'how much' },
      { t: 'cuál', e: 'which' },
      { t: 'porque', e: 'because', n: 'One word and no accent — porque is "because", por qué is "why".' },
      { t: 'quizás', e: 'maybe' },
      { t: 'siempre', e: 'always' },
      { t: 'nunca', e: 'never' },
      { t: 'ahora', e: 'now' },
      { t: 'después', e: 'afterwards' },
      { t: 'todavía', e: 'still' },
      { t: 'ya', e: 'already' }
    ],
    sentences: [
      { t: '¿ Qué es esto ?', e: 'what is this ?' },
      { t: '¿ Por qué no vienes ?', e: 'why are you not coming ?' },
      { t: 'Porque estoy ocupado', e: 'because I am busy' },
      { t: '¿ Cuánto cuesta ?', e: 'how much does it cost ?' },
      { t: '¿ Cuándo llega el tren ?', e: 'when does the train arrive ?' },
      { t: 'Nunca como carne', e: 'I never eat meat' },
      { t: '¿ Cuál prefieres ?', e: 'which one do you prefer ?' }
    ] },

  { id: 'es-time', kind: 'words', title: 'Time and days',
    blurb: 'Telling the time, and saying when.',
    vocab: [
      { t: 'hoy', e: 'today' },
      { t: 'mañana', e: 'tomorrow', n: 'Also means "morning": la mañana. Context tells you which.' },
      { t: 'ayer', e: 'yesterday' },
      { t: 'la hora', e: 'the hour', g: 'f' },
      { t: 'el día', e: 'the day', g: 'm', n: 'Masculine despite the -a. One of the handful worth memorising.' },
      { t: 'la semana', e: 'the week', g: 'f' },
      { t: 'el mes', e: 'the month', g: 'm' },
      { t: 'el año', e: 'the year', g: 'm' },
      { t: 'lunes', e: 'Monday' },
      { t: 'martes', e: 'Tuesday' },
      { t: 'miércoles', e: 'Wednesday' },
      { t: 'jueves', e: 'Thursday' },
      { t: 'viernes', e: 'Friday' },
      { t: 'sábado', e: 'Saturday' },
      { t: 'domingo', e: 'Sunday' },
      { t: 'la noche', e: 'the night', g: 'f' },
      { t: 'temprano', e: 'early' },
      { t: 'tarde', e: 'late' }
    ],
    sentences: [
      { t: '¿ Qué hora es ?', e: 'what time is it ?' },
      { t: 'Hoy es lunes', e: 'today is Monday', n: 'Days are not capitalised in Spanish.' },
      { t: 'Trabajo por la mañana', e: 'I work in the morning' },
      { t: 'Nos vemos mañana', e: 'see you tomorrow' },
      { t: 'La reunión es el viernes', e: 'the meeting is on Friday' },
      { t: 'Llego muy tarde', e: 'I am arriving very late' },
      { t: 'Este año quiero viajar', e: 'this year I want to travel' }
    ] },

  { id: 'es-shop', kind: 'words', title: 'Shopping and money',
    blurb: 'Buying things, and asking what they cost.',
    vocab: [
      { t: 'el dinero', e: 'the money', g: 'm' },
      { t: 'el precio', e: 'the price', g: 'm' },
      { t: 'la tarjeta', e: 'the card', g: 'f' },
      { t: 'el efectivo', e: 'the cash', g: 'm' },
      { t: 'comprar', e: 'to buy' },
      { t: 'vender', e: 'to sell' },
      { t: 'pagar', e: 'to pay' },
      { t: 'costar', e: 'to cost' },
      { t: 'la ropa', e: 'the clothes', g: 'f', n: 'Singular in Spanish — la ropa es cara, never son.' },
      { t: 'la camisa', e: 'the shirt', g: 'f' },
      { t: 'los zapatos', e: 'the shoes' },
      { t: 'el bolso', e: 'the bag', g: 'm' },
      { t: 'el regalo', e: 'the gift', g: 'm' },
      { t: 'abierto', e: 'open' },
      { t: 'cerrado', e: 'closed' },
      { t: 'gratis', e: 'free of charge' },
      { t: 'otro', e: 'another' },
      { t: 'todo', e: 'everything' }
    ],
    sentences: [
      { t: '¿ Cuánto cuesta esta camisa ?', e: 'how much does this shirt cost ?' },
      { t: 'Quiero pagar con tarjeta', e: 'I want to pay by card' },
      { t: 'Es demasiado caro', e: 'it is too expensive' },
      { t: 'La tienda está cerrada', e: 'the shop is closed' },
      { t: 'No tengo dinero', e: 'I do not have money' },
      { t: '¿ Tiene otro color ?', e: 'do you have another colour ?' },
      { t: 'Voy a comprar un regalo', e: 'I am going to buy a gift' }
    ] },

  { id: 'es-home', kind: 'words', title: 'Home and routine',
    blurb: 'The house, and what you do in a day.',
    vocab: [
      { t: 'la puerta', e: 'the door', g: 'f' },
      { t: 'la ventana', e: 'the window', g: 'f' },
      { t: 'la mesa', e: 'the table', g: 'f' },
      { t: 'la silla', e: 'the chair', g: 'f' },
      { t: 'la cama', e: 'the bed', g: 'f' },
      { t: 'la cocina', e: 'the kitchen', g: 'f' },
      { t: 'el cuarto', e: 'the room', g: 'm' },
      { t: 'la llave', e: 'the key', g: 'f' },
      { t: 'el libro', e: 'the book', g: 'm' },
      { t: 'el teléfono', e: 'the telephone', g: 'm' },
      { t: 'dormir', e: 'to sleep' },
      { t: 'despertarse', e: 'to wake up' },
      { t: 'lavar', e: 'to wash' },
      { t: 'limpiar', e: 'to clean' },
      { t: 'cocinar', e: 'to cook' },
      { t: 'descansar', e: 'to rest' },
      { t: 'abrir', e: 'to open' },
      { t: 'cerrar', e: 'to close' }
    ],
    sentences: [
      { t: 'Me despierto a las siete', e: 'I wake up at seven', n: 'Me despierto is reflexive — literally "I wake myself up".' },
      { t: 'Cocino todos los días', e: 'I cook every day' },
      { t: 'El libro está en la mesa', e: 'the book is on the table' },
      { t: '¿ Puedes abrir la ventana ?', e: 'can you open the window ?' },
      { t: 'Necesito limpiar la cocina', e: 'I need to clean the kitchen' },
      { t: 'No encuentro mis llaves', e: 'I cannot find my keys' },
      { t: 'Voy a descansar un poco', e: 'I am going to rest a little' }
    ] },

  { id: 'es-travel', kind: 'words', title: 'Travel',
    blurb: 'Getting from one place to another.',
    vocab: [
      { t: 'el coche', e: 'the car', g: 'm', n: 'El carro in most of Latin America; el coche in Spain and Mexico.' },
      { t: 'el autobús', e: 'the bus', g: 'm' },
      { t: 'el tren', e: 'the train', g: 'm' },
      { t: 'el avión', e: 'the aeroplane', g: 'm' },
      { t: 'el aeropuerto', e: 'the airport', g: 'm' },
      { t: 'el boleto', e: 'the ticket', g: 'm' },
      { t: 'la maleta', e: 'the suitcase', g: 'f' },
      { t: 'el viaje', e: 'the trip', g: 'm' },
      { t: 'el mapa', e: 'the map', g: 'm', n: 'Masculine despite the -a: el mapa, from Greek.' },
      { t: 'viajar', e: 'to travel' },
      { t: 'llegar', e: 'to arrive' },
      { t: 'salir', e: 'to leave' },
      { t: 'esperar', e: 'to wait' },
      { t: 'perder', e: 'to lose' },
      { t: 'caminar', e: 'to walk' },
      { t: 'el camino', e: 'the road', g: 'm' },
      { t: 'primera vez', e: 'first time' },
      { t: 'el país', e: 'the country', g: 'm' }
    ],
    sentences: [
      { t: '¿ A qué hora sale el tren ?', e: 'what time does the train leave ?' },
      { t: 'Perdí mi maleta', e: 'I lost my suitcase' },
      { t: 'Quiero un boleto a Madrid', e: 'I want a ticket to Madrid' },
      { t: 'El avión llega a las nueve', e: 'the aeroplane arrives at nine' },
      { t: 'Es mi primera vez aquí', e: 'it is my first time here' },
      { t: 'Vamos a viajar en tren', e: 'we are going to travel by train' },
      { t: '¿ Dónde está el aeropuerto ?', e: 'where is the airport ?' }
    ] },

  { id: 'es-past', kind: 'words', title: 'The past',
    blurb: 'Saying what happened. The preterite, for finished actions.',
    vocab: [
      { t: 'fui', e: 'I went', n: 'Also "I was" — ser and ir share this past tense. Context tells you which.' },
      { t: 'fue', e: 'he went' },
      { t: 'estuve', e: 'I was located' },
      { t: 'tuve', e: 'I had' },
      { t: 'hice', e: 'I did' },
      { t: 'dije', e: 'I said' },
      { t: 'vi', e: 'I saw' },
      { t: 'comí', e: 'I ate' },
      { t: 'hablé', e: 'I spoke', n: 'Regular -ar past: hablé, hablaste, habló, hablamos, hablaron. The accent carries the stress.' },
      { t: 'viví', e: 'I lived' },
      { t: 'compré', e: 'I bought' },
      { t: 'llegué', e: 'I arrived' },
      { t: 'anoche', e: 'last night' },
      { t: 'la semana pasada', e: 'last week' },
      { t: 'antes', e: 'before' },
      { t: 'entonces', e: 'then' },
      { t: 'nacer', e: 'to be born' },
      { t: 'conocer', e: 'to meet' }
    ],
    sentences: [
      { t: 'Ayer fui al mercado', e: 'yesterday I went to the market' },
      { t: 'Comí en un restaurante', e: 'I ate at a restaurant' },
      { t: '¿ Qué hiciste anoche ?', e: 'what did you do last night ?' },
      { t: 'No dije nada', e: 'I did not say anything', n: 'Spanish stacks negatives: no dije nada is literally "I did not say nothing".' },
      { t: 'La semana pasada estuve enfermo', e: 'last week I was ill' },
      { t: 'Nací en Canadá', e: 'I was born in Canada' },
      { t: 'La conocí el año pasado', e: 'I met her last year' }
    ] },

  { id: 'es-future', kind: 'words', title: 'Plans and the future',
    blurb: 'What you are going to do. The easy future first.',
    vocab: [
      { t: 'voy a', e: 'I am going to', n: 'ir a + infinitive is how Spanish usually talks about the future: voy a comer.' },
      { t: 'vas a', e: 'you are going to' },
      { t: 'va a', e: 'he is going to' },
      { t: 'vamos a', e: 'we are going to' },
      { t: 'poder', e: 'to be able to' },
      { t: 'puedo', e: 'I can' },
      { t: 'deber', e: 'to have to' },
      { t: 'debo', e: 'I must' },
      { t: 'empezar', e: 'to begin' },
      { t: 'terminar', e: 'to finish' },
      { t: 'seguir', e: 'to continue' },
      { t: 'intentar', e: 'to try' },
      { t: 'el plan', e: 'the plan', g: 'm' },
      { t: 'pronto', e: 'soon' },
      { t: 'luego', e: 'later' },
      { t: 'próximo', e: 'next' },
      { t: 'juntos', e: 'together' },
      { t: 'tal vez', e: 'perhaps' }
    ],
    sentences: [
      { t: 'Voy a estudiar español', e: 'I am going to study Spanish' },
      { t: '¿ Puedes ayudarme ?', e: 'can you help me ?' },
      { t: 'Debo trabajar mañana', e: 'I must work tomorrow' },
      { t: 'Vamos a comer juntos', e: 'we are going to eat together' },
      { t: 'El próximo mes voy a viajar', e: 'next month I am going to travel' },
      { t: 'Voy a intentar otra vez', e: 'I am going to try again' },
      { t: 'Tal vez llegue tarde', e: 'perhaps I will arrive late' }
    ] },

  { id: 'es-body', kind: 'words', title: 'Health and the body',
    blurb: 'Saying what hurts.',
    vocab: [
      { t: 'la cabeza', e: 'the head', g: 'f' },
      { t: 'el ojo', e: 'the eye', g: 'm' },
      { t: 'la boca', e: 'the mouth', g: 'f' },
      { t: 'la mano', e: 'the hand', g: 'f', n: 'Feminine despite the -o: la mano, las manos.' },
      { t: 'el pie', e: 'the foot', g: 'm' },
      { t: 'el brazo', e: 'the arm', g: 'm' },
      { t: 'la pierna', e: 'the leg', g: 'f' },
      { t: 'el estómago', e: 'the stomach', g: 'm' },
      { t: 'la espalda', e: 'the back', g: 'f' },
      { t: 'el dolor', e: 'the pain', g: 'm' },
      { t: 'enfermo', e: 'ill' },
      { t: 'sano', e: 'healthy' },
      { t: 'doler', e: 'to hurt' },
      { t: 'la farmacia', e: 'the pharmacy', g: 'f' },
      { t: 'la medicina', e: 'the medicine', g: 'f' },
      { t: 'la cita', e: 'the appointment', g: 'f' },
      { t: 'ayudar', e: 'to help' },
      { t: 'sentirse', e: 'to feel' }
    ],
    sentences: [
      { t: 'Me duele la cabeza', e: 'my head hurts', n: 'Literally "the head hurts to me". Spanish rarely uses "my" for body parts.' },
      { t: 'Estoy enfermo hoy', e: 'I am ill today' },
      { t: '¿ Cómo te sientes ?', e: 'how do you feel ?' },
      { t: 'Necesito una farmacia', e: 'I need a pharmacy' },
      { t: 'Me duelen los pies', e: 'my feet hurt' },
      { t: 'Tengo una cita con el médico', e: 'I have an appointment with the doctor' },
      { t: '¿ Puede ayudarme , por favor ?', e: 'can you help me , please ?' }
    ] },

  { id: 'es-weather', kind: 'words', title: 'Weather and seasons',
    blurb: 'Small talk, everywhere in the world.',
    vocab: [
      { t: 'el tiempo', e: 'the weather', g: 'm', n: 'Also means "time" in general: no tengo tiempo.' },
      { t: 'el sol', e: 'the sun', g: 'm' },
      { t: 'la lluvia', e: 'the rain', g: 'f' },
      { t: 'la nieve', e: 'the snow', g: 'f' },
      { t: 'el viento', e: 'the wind', g: 'm' },
      { t: 'la nube', e: 'the cloud', g: 'f' },
      { t: 'el calor', e: 'the heat', g: 'm' },
      { t: 'el invierno', e: 'the winter', g: 'm' },
      { t: 'la primavera', e: 'the spring', g: 'f' },
      { t: 'el verano', e: 'the summer', g: 'm' },
      { t: 'el otoño', e: 'the autumn', g: 'm' },
      { t: 'llover', e: 'to rain' },
      { t: 'nevar', e: 'to snow' },
      { t: 'hace', e: 'it is', n: 'Weather uses hacer: hace frío, hace calor, hace sol. Literally "it makes cold".' },
      { t: 'afuera', e: 'outside' },
      { t: 'adentro', e: 'inside' }
    ],
    sentences: [
      { t: 'Hace mucho frío hoy', e: 'it is very cold today' },
      { t: 'Está lloviendo afuera', e: 'it is raining outside' },
      { t: 'En invierno nieva mucho', e: 'in winter it snows a lot' },
      { t: 'Hace calor en verano', e: 'it is hot in summer' },
      { t: '¿ Qué tiempo hace ?', e: 'what is the weather like ?' },
      { t: 'Me gusta la primavera', e: 'I like the spring' }
    ] },

  { id: 'es-feel', kind: 'words', title: 'Feelings and opinions',
    blurb: 'Saying what you think, which is where conversation starts.',
    vocab: [
      { t: 'feliz', e: 'happy' },
      { t: 'triste', e: 'sad' },
      { t: 'enojado', e: 'angry' },
      { t: 'contento', e: 'pleased' },
      { t: 'nervioso', e: 'nervous' },
      { t: 'tranquilo', e: 'calm' },
      { t: 'creer', e: 'to believe' },
      { t: 'creo', e: 'I think' },
      { t: 'pensar', e: 'to think' },
      { t: 'gustar', e: 'to please' },
      { t: 'encantar', e: 'to love', n: 'Works like gustar: me encanta el café, "coffee delights me".' },
      { t: 'preferir', e: 'to prefer' },
      { t: 'odiar', e: 'to hate' },
      { t: 'la idea', e: 'the idea', g: 'f' },
      { t: 'la verdad', e: 'the truth', g: 'f' },
      { t: 'de acuerdo', e: 'in agreement' },
      { t: 'genial', e: 'great' },
      { t: 'aburrido', e: 'boring' }
    ],
    sentences: [
      { t: 'Creo que tienes razón', e: 'I think you are right' },
      { t: 'Me encanta este lugar', e: 'I love this place' },
      { t: 'Estoy muy feliz hoy', e: 'I am very happy today' },
      { t: 'No estoy de acuerdo', e: 'I do not agree' },
      { t: '¿ Qué piensas tú ?', e: 'what do you think ?' },
      { t: 'Prefiero el té', e: 'I prefer tea' },
      { t: 'La película fue aburrida', e: 'the film was boring' }
    ] },

  { id: 'es-work', kind: 'words', title: 'Work and study',
    blurb: 'What you do, and what you are learning.',
    vocab: [
      { t: 'el trabajo', e: 'the job', g: 'm' },
      { t: 'la empresa', e: 'the company', g: 'f' },
      { t: 'el jefe', e: 'the boss', g: 'm' },
      { t: 'la reunión', e: 'the meeting', g: 'f' },
      { t: 'el correo', e: 'the email', g: 'm' },
      { t: 'la universidad', e: 'the university', g: 'f' },
      { t: 'la clase', e: 'the class', g: 'f' },
      { t: 'el examen', e: 'the exam', g: 'm' },
      { t: 'la pregunta', e: 'the question', g: 'f' },
      { t: 'la respuesta', e: 'the answer', g: 'f' },
      { t: 'estudiar', e: 'to study' },
      { t: 'aprender', e: 'to learn' },
      { t: 'enseñar', e: 'to teach' },
      { t: 'escribir', e: 'to write' },
      { t: 'practicar', e: 'to practise' },
      { t: 'la palabra', e: 'the word', g: 'f' },
      { t: 'el idioma', e: 'the language', g: 'm', n: 'Masculine despite the -a, like el problema and el sistema.' },
      { t: 'el proyecto', e: 'the project', g: 'm' }
    ],
    sentences: [
      { t: 'Estudio español todos los días', e: 'I study Spanish every day' },
      { t: 'Tengo una reunión a las tres', e: 'I have a meeting at three' },
      { t: '¿ Cuál es tu trabajo ?', e: 'what is your job ?' },
      { t: 'Quiero aprender otro idioma', e: 'I want to learn another language' },
      { t: 'No sé la respuesta', e: 'I do not know the answer' },
      { t: 'Ella enseña en la universidad', e: 'she teaches at the university' },
      { t: 'Necesito practicar más', e: 'I need to practise more' }
    ] },

  { id: 'es-connect', kind: 'words', title: 'Putting sentences together',
    blurb: 'The small words that turn phrases into speech.',
    vocab: [
      { t: 'y', e: 'and' },
      { t: 'pero', e: 'but' },
      { t: 'o', e: 'or' },
      { t: 'si', e: 'if', n: 'No accent. Sí with an accent is "yes".' },
      { t: 'cuando', e: 'when', n: 'No accent in a statement; ¿cuándo? with one in a question.' },
      { t: 'aunque', e: 'although' },
      { t: 'así que', e: 'so' },
      { t: 'además', e: 'besides' },
      { t: 'sin embargo', e: 'however' },
      { t: 'por eso', e: 'that is why' },
      { t: 'mientras', e: 'while' },
      { t: 'sobre', e: 'about' },
      { t: 'para', e: 'for', n: 'Para is purpose or destination; por is cause or exchange. The most argued-over pair in Spanish.' },
      { t: 'por', e: 'by' },
      { t: 'sin', e: 'without' },
      { t: 'hasta', e: 'until' },
      { t: 'desde', e: 'since' },
      { t: 'algo', e: 'something' }
    ],
    sentences: [
      { t: 'Quiero ir pero estoy cansado', e: 'I want to go but I am tired' },
      { t: 'Si llueve , no salimos', e: 'if it rains , we are not going out' },
      { t: 'Estudio español porque me gusta', e: 'I study Spanish because I like it' },
      { t: 'Trabajo y después descanso', e: 'I work and afterwards I rest' },
      { t: 'Aunque es difícil , sigo', e: 'although it is difficult , I continue' },
      { t: 'Hablamos sobre el viaje', e: 'we talked about the trip' },
      { t: 'Este regalo es para ti', e: 'this gift is for you' },
      { t: 'No puedo vivir sin café', e: 'I cannot live without coffee' }
    ] }

  ]
};

Courses.register(SPANISH);
})();
