/* Lisan — the German course.
 *
 * Standard German. Pronunciation is derived by rule rather than stored, which
 * German allows because its spelling is genuinely regular — an explicit `p`
 * appears only where a word breaks the rules or is a loan.
 *
 * Nouns are introduced with der, die or das, and always capitalised, because
 * both are part of the word: German has three genders and no reliable way to
 * guess which one a noun takes.
 */
(function () {
'use strict';

var GERMAN = {
  id: 'de',
  name: 'German',
  native: 'Deutsch',
  dir: 'ltr',
  script: 'latin',
  speech: ['de-DE', 'de-AT', 'de'],
  gendered: true,
  order: 5,
  blurb: 'Standard German — closely related to English, which helps more than the grammar hurts.',
  grammar: {
    wordOrder: 'The conjugated verb is the second element of a main clause, whatever comes first: ' +
               'Ich gehe heute, but Heute gehe ich. In a subordinate clause it goes to the very end.',
    articles: { m: 'der', f: 'die', n: 'das' },
    genderNote: 'Three genders and no reliable rule, though -ung, -heit, -keit and -schaft are always ' +
                'die, and -chen is always das — even das Mädchen, "the girl".'
  },
  units: [

  { id: 'de-greet', kind: 'words', title: 'Greetings',
    blurb: 'Opening and closing a conversation.',
    vocab: [
      { t: 'hallo', e: 'hello' },
      { t: 'guten Morgen', e: 'good morning' },
      { t: 'guten Tag', e: 'good day' },
      { t: 'guten Abend', e: 'good evening' },
      { t: 'tschüss', e: 'bye', p: 'CHEWS' },
      { t: 'auf Wiedersehen', e: 'goodbye' },
      { t: 'danke', e: 'thank you' },
      { t: 'bitte', e: 'please', n: 'Also "you are welcome", and "pardon?" — one of the hardest-working words in German.' },
      { t: 'entschuldigung', e: 'excuse me' },
      { t: 'ja', e: 'yes' },
      { t: 'nein', e: 'no' },
      { t: 'vielleicht', e: 'maybe' },
      { t: 'gut', e: 'good' },
      { t: 'schlecht', e: 'bad' },
      { t: 'freut mich', e: 'pleased to meet you' },
      { t: 'bis später', e: 'see you later' },
      { t: 'gute Nacht', e: 'good night' },
      { t: 'genau', e: 'exactly' }
    ],
    sentences: [
      { t: 'Wie geht es dir ?', e: 'how are you ?' },
      { t: 'Mir geht es gut , danke', e: 'I am well , thank you' },
      { t: 'Wie heißt du ?', e: 'what is your name ?' },
      { t: 'Ich heiße Anna', e: 'my name is Anna' },
      { t: 'Freut mich , Anna', e: 'pleased to meet you , Anna' },
      { t: 'Vielen Dank für alles', e: 'many thanks for everything' },
      { t: 'Bis später , Freund', e: 'see you later , friend' }
    ] },

  { id: 'de-people', kind: 'words', title: 'People',
    blurb: 'Pronouns, and who you are talking about.',
    vocab: [
      { t: 'ich', e: 'I' },
      { t: 'du', e: 'you', n: 'Informal. Use Sie — always capitalised — with strangers and at work.' },
      { t: 'Sie', e: 'you formal' },
      { t: 'er', e: 'he' },
      { t: 'sie', e: 'she' },
      { t: 'wir', e: 'we' },
      { t: 'der Mann', e: 'the man', g: 'm', n: 'Also means "husband" — mein Mann is my husband.' },
      { t: 'die Frau', e: 'the woman', g: 'f' },
      { t: 'der Junge', e: 'the boy', g: 'm' },
      { t: 'das Mädchen', e: 'the girl', g: 'n', n: 'Neuter, not feminine — every -chen word is das, whatever it means.' },
      { t: 'das Kind', e: 'the child', g: 'n' },
      { t: 'der Freund', e: 'the friend', g: 'm' },
      { t: 'die Leute', e: 'the people' },
      { t: 'der Nachbar', e: 'the neighbour', g: 'm' },
      { t: 'der Name', e: 'the name', g: 'm' },
      { t: 'jemand', e: 'someone' },
      { t: 'niemand', e: 'nobody' },
      { t: 'alle', e: 'everyone' }
    ],
    sentences: [
      { t: 'Ich bin Student', e: 'I am a student', n: 'German drops "a" before a job: ich bin Student.' },
      { t: 'Sie ist meine Freundin', e: 'she is my friend' },
      { t: 'Er ist sehr nett', e: 'he is very kind' },
      { t: 'Wir sind Freunde', e: 'we are friends' },
      { t: 'Wer ist diese Frau ?', e: 'who is that woman ?' },
      { t: 'Mein Nachbar spricht Deutsch', e: 'my neighbour speaks German' }
    ] },

  { id: 'de-sein', kind: 'words', title: 'To be and to have',
    blurb: 'sein and haben, the two verbs everything leans on.',
    vocab: [
      { t: 'sein', e: 'to be' },
      { t: 'ich bin', e: 'I am' },
      { t: 'du bist', e: 'you are' },
      { t: 'er ist', e: 'he is' },
      { t: 'wir sind', e: 'we are' },
      { t: 'haben', e: 'to have' },
      { t: 'ich habe', e: 'I have' },
      { t: 'du hast', e: 'you have' },
      { t: 'er hat', e: 'he has' },
      { t: 'wir haben', e: 'we have' },
      { t: 'kanadisch', e: 'Canadian' },
      { t: 'deutsch', e: 'German' },
      { t: 'der Lehrer', e: 'the teacher', g: 'm' },
      { t: 'der Arzt', e: 'the doctor', g: 'm' },
      { t: 'müde', e: 'tired' },
      { t: 'beschäftigt', e: 'busy' },
      { t: 'hungrig', e: 'hungry' },
      { t: 'durstig', e: 'thirsty' }
    ],
    sentences: [
      { t: 'Ich bin Kanadier', e: 'I am Canadian' },
      { t: 'Ich habe zwei Brüder', e: 'I have two brothers' },
      { t: 'Sie ist Lehrerin', e: 'she is a teacher', n: 'Female job titles take -in: Lehrer becomes Lehrerin, Arzt becomes Ärztin.' },
      { t: 'Ich bin sehr müde', e: 'I am very tired' },
      { t: 'Wir sind hungrig', e: 'we are hungry' },
      { t: 'Er ist zwanzig Jahre alt', e: 'he is twenty years old' },
      { t: 'Bist du beschäftigt ?', e: 'are you busy ?' }
    ] },

  { id: 'de-family', kind: 'words', title: 'Family',
    blurb: 'The people you mention most.',
    vocab: [
      { t: 'die Familie', e: 'the family', g: 'f' },
      { t: 'der Vater', e: 'the father', g: 'm' },
      { t: 'die Mutter', e: 'the mother', g: 'f' },
      { t: 'der Bruder', e: 'the brother', g: 'm' },
      { t: 'die Schwester', e: 'the sister', g: 'f' },
      { t: 'der Sohn', e: 'the son', g: 'm' },
      { t: 'die Tochter', e: 'the daughter', g: 'f' },
      { t: 'die Eltern', e: 'the parents' },
      { t: 'der Großvater', e: 'the grandfather', g: 'm' },
      { t: 'die Großmutter', e: 'the grandmother', g: 'f' },
      { t: 'die Geschwister', e: 'the siblings' },
      { t: 'die Tante', e: 'the aunt', g: 'f' },
      { t: 'der Onkel', e: 'the uncle', g: 'm' },
      { t: 'mein', e: 'my' },
      { t: 'dein', e: 'your' },
      { t: 'unser', e: 'our' },
      { t: 'ihr', e: 'her' },
      { t: 'zusammen', e: 'together' }
    ],
    sentences: [
      { t: 'Ich habe eine Schwester', e: 'I have one sister' },
      { t: 'Meine Mutter heißt Elena', e: 'my mother is called Elena' },
      { t: 'Meine Eltern wohnen hier', e: 'my parents live here' },
      { t: 'Hast du Geschwister ?', e: 'do you have siblings ?' },
      { t: 'Sein Vater ist Arzt', e: 'his father is a doctor' },
      { t: 'Unsere Familie ist groß', e: 'our family is big' }
    ] },

  { id: 'de-num', kind: 'words', title: 'Numbers',
    blurb: 'One to a hundred. The tens come after the units.',
    vocab: [
      { t: 'eins', e: 'one' },
      { t: 'zwei', e: 'two' },
      { t: 'drei', e: 'three' },
      { t: 'vier', e: 'four' },
      { t: 'fünf', e: 'five' },
      { t: 'sechs', e: 'six' },
      { t: 'sieben', e: 'seven' },
      { t: 'acht', e: 'eight' },
      { t: 'neun', e: 'nine' },
      { t: 'zehn', e: 'ten' },
      { t: 'elf', e: 'eleven' },
      { t: 'zwölf', e: 'twelve' },
      { t: 'zwanzig', e: 'twenty' },
      { t: 'einundzwanzig', e: 'twenty-one', n: 'Literally "one-and-twenty". German says the unit first, all the way up.' },
      { t: 'dreißig', e: 'thirty' },
      { t: 'hundert', e: 'one hundred' },
      { t: 'viel', e: 'a lot' },
      { t: 'wenig', e: 'a little' },
      { t: 'erste', e: 'first' },
      { t: 'das Jahr', e: 'the year', g: 'n' }
    ],
    sentences: [
      { t: 'Ich bin dreißig Jahre alt', e: 'I am thirty years old' },
      { t: 'Das kostet zehn Euro', e: 'that costs ten euros' },
      { t: 'Es gibt drei Leute hier', e: 'there are three people here', n: 'Es gibt is "there is" and "there are" — literally "it gives".' },
      { t: 'Ich möchte zwei , bitte', e: 'I would like two , please' },
      { t: 'Wie alt bist du ?', e: 'how old are you ?' }
    ] },

  { id: 'de-food', kind: 'words', title: 'Food and drink',
    blurb: 'Ordering, and saying what you like.',
    vocab: [
      { t: 'das Wasser', e: 'the water', g: 'n' },
      { t: 'das Brot', e: 'the bread', g: 'n' },
      { t: 'der Käse', e: 'the cheese', g: 'm' },
      { t: 'das Fleisch', e: 'the meat', g: 'n' },
      { t: 'das Hähnchen', e: 'the chicken', g: 'n' },
      { t: 'der Fisch', e: 'the fish', g: 'm' },
      { t: 'das Ei', e: 'the egg', g: 'n' },
      { t: 'die Milch', e: 'the milk', g: 'f' },
      { t: 'der Kaffee', e: 'the coffee', g: 'm' },
      { t: 'der Tee', e: 'the tea', g: 'm' },
      { t: 'das Bier', e: 'the beer', g: 'n' },
      { t: 'der Apfel', e: 'the apple', g: 'm' },
      { t: 'das Salz', e: 'the salt', g: 'n' },
      { t: 'das Essen', e: 'the food', g: 'n' },
      { t: 'das Restaurant', e: 'the restaurant', g: 'n', p: 'res-toh-RAHNG' },
      { t: 'die Rechnung', e: 'the bill', g: 'f' },
      { t: 'essen', e: 'to eat' },
      { t: 'trinken', e: 'to drink' },
      { t: 'lecker', e: 'delicious' },
      { t: 'das Frühstück', e: 'the breakfast', g: 'n' }
    ],
    sentences: [
      { t: 'Ich möchte einen Kaffee , bitte', e: 'I would like a coffee , please', n: 'Ich möchte is the polite way to order — far softer than ich will.' },
      { t: 'Das Brot ist lecker', e: 'the bread is delicious' },
      { t: 'Ich esse kein Fleisch', e: 'I do not eat meat', n: 'kein negates a noun; nicht negates everything else.' },
      { t: 'Die Rechnung , bitte', e: 'the bill , please' },
      { t: 'Was möchtest du essen ?', e: 'what would you like to eat ?' },
      { t: 'Ich trinke gern Tee', e: 'I like drinking tea', n: 'gern after a verb means you like doing it. There is no verb "to like" needed.' }
    ] },

  { id: 'de-places', kind: 'words', title: 'Places',
    blurb: 'Where things are, and how to ask.',
    vocab: [
      { t: 'das Haus', e: 'the house', g: 'n' },
      { t: 'die Schule', e: 'the school', g: 'f' },
      { t: 'der Markt', e: 'the market', g: 'm' },
      { t: 'die Stadt', e: 'the city', g: 'f' },
      { t: 'die Straße', e: 'the street', g: 'f' },
      { t: 'das Hotel', e: 'the hotel', g: 'n' },
      { t: 'das Krankenhaus', e: 'the hospital', g: 'n', n: 'Literally "sick house". German builds long words out of short ones.' },
      { t: 'das Büro', e: 'the office', g: 'n' },
      { t: 'das Geschäft', e: 'the shop', g: 'n' },
      { t: 'die Toilette', e: 'the toilet', g: 'f' },
      { t: 'hier', e: 'here' },
      { t: 'dort', e: 'there' },
      { t: 'nah', e: 'near' },
      { t: 'weit', e: 'far' },
      { t: 'rechts', e: 'on the right' },
      { t: 'links', e: 'on the left' },
      { t: 'geradeaus', e: 'straight ahead' },
      { t: 'zu Hause', e: 'at home' }
    ],
    sentences: [
      { t: 'Wo ist die Toilette ?', e: 'where is the toilet ?' },
      { t: 'Der Markt ist nah', e: 'the market is near' },
      { t: 'Ich wohne in einer großen Stadt', e: 'I live in a big city' },
      { t: 'Das Geschäft ist rechts', e: 'the shop is on the right' },
      { t: 'Ich gehe zur Schule', e: 'I go to school' },
      { t: 'Ist es weit von hier ?', e: 'is it far from here ?' }
    ] },

  { id: 'de-verbs', kind: 'words', title: 'Everyday verbs',
    blurb: 'The present tense, and where the verb sits.',
    vocab: [
      { t: 'sprechen', e: 'to speak' },
      { t: 'ich spreche', e: 'I speak' },
      { t: 'gehen', e: 'to go' },
      { t: 'ich gehe', e: 'I go' },
      { t: 'machen', e: 'to do' },
      { t: 'ich mache', e: 'I do' },
      { t: 'wollen', e: 'to want' },
      { t: 'ich will', e: 'I want' },
      { t: 'können', e: 'to be able to' },
      { t: 'ich kann', e: 'I can' },
      { t: 'wissen', e: 'to know' },
      { t: 'ich weiß', e: 'I know' },
      { t: 'wohnen', e: 'to live' },
      { t: 'arbeiten', e: 'to work' },
      { t: 'verstehen', e: 'to understand' },
      { t: 'lesen', e: 'to read' },
      { t: 'schreiben', e: 'to write' },
      { t: 'kommen', e: 'to come' },
      { t: 'sehen', e: 'to see' },
      { t: 'brauchen', e: 'to need' }
    ],
    sentences: [
      { t: 'Ich spreche ein bisschen Deutsch', e: 'I speak a little German' },
      { t: 'Ich verstehe nicht', e: 'I do not understand' },
      { t: 'Sprichst du Englisch ?', e: 'do you speak English ?' },
      { t: 'Ich arbeite in einem Büro', e: 'I work in an office' },
      { t: 'Ich brauche Hilfe', e: 'I need help' },
      { t: 'Heute gehe ich zum Markt', e: 'today I go to the market', n: 'Heute comes first, so the verb still takes second place and ich moves behind it.' },
      { t: 'Was machst du ?', e: 'what are you doing ?' }
    ] },

  { id: 'de-desc', kind: 'words', title: 'Describing things',
    blurb: 'Adjectives, before the noun as in English.',
    vocab: [
      { t: 'groß', e: 'big' },
      { t: 'klein', e: 'small' },
      { t: 'neu', e: 'new' },
      { t: 'alt', e: 'old' },
      { t: 'schön', e: 'beautiful' },
      { t: 'hässlich', e: 'ugly' },
      { t: 'teuer', e: 'expensive' },
      { t: 'billig', e: 'cheap' },
      { t: 'einfach', e: 'easy' },
      { t: 'schwer', e: 'difficult', n: 'Also means "heavy".' },
      { t: 'schnell', e: 'fast' },
      { t: 'langsam', e: 'slow' },
      { t: 'heiß', e: 'hot' },
      { t: 'kalt', e: 'cold' },
      { t: 'lang', e: 'long' },
      { t: 'kurz', e: 'short' },
      { t: 'sehr', e: 'very' },
      { t: 'mehr', e: 'more' },
      { t: 'nett', e: 'kind' },
      { t: 'richtig', e: 'correct' }
    ],
    sentences: [
      { t: 'Das Haus ist sehr groß', e: 'the house is very big' },
      { t: 'Es ist ein neues Buch', e: 'it is a new book', n: 'An adjective before a noun takes an ending; after sein it never does.' },
      { t: 'Deutsch ist nicht schwer', e: 'German is not difficult' },
      { t: 'Dieser Kaffee ist zu heiß', e: 'this coffee is too hot' },
      { t: 'Mein Auto ist alt', e: 'my car is old' },
      { t: 'Das ist richtig', e: 'that is correct' }
    ] },

  { id: 'de-quest', kind: 'words', title: 'Questions',
    blurb: 'The W-words, all of which start with w.',
    vocab: [
      { t: 'wer', e: 'who' },
      { t: 'was', e: 'what' },
      { t: 'wo', e: 'where' },
      { t: 'wann', e: 'when' },
      { t: 'warum', e: 'why' },
      { t: 'wie', e: 'how' },
      { t: 'wie viel', e: 'how much' },
      { t: 'welcher', e: 'which' },
      { t: 'weil', e: 'because', n: 'weil sends the verb to the end of its clause: ich bleibe, weil ich müde bin.' },
      { t: 'immer', e: 'always' },
      { t: 'nie', e: 'never' },
      { t: 'jetzt', e: 'now' },
      { t: 'oft', e: 'often' },
      { t: 'manchmal', e: 'sometimes' },
      { t: 'schon', e: 'already' },
      { t: 'noch', e: 'still' }
    ],
    sentences: [
      { t: 'Was ist das ?', e: 'what is that ?' },
      { t: 'Warum kommst du nicht ?', e: 'why are you not coming ?' },
      { t: 'Weil ich müde bin', e: 'because I am tired' },
      { t: 'Wie viel kostet das ?', e: 'how much does that cost ?' },
      { t: 'Wann kommt der Zug ?', e: 'when does the train come ?' },
      { t: 'Ich esse nie Fleisch', e: 'I never eat meat' }
    ] },

  { id: 'de-time', kind: 'words', title: 'Time and days',
    blurb: 'Telling the time, and saying when.',
    vocab: [
      { t: 'heute', e: 'today' },
      { t: 'morgen', e: 'tomorrow', n: 'der Morgen with a capital M is "the morning". Same word, different job.' },
      { t: 'gestern', e: 'yesterday' },
      { t: 'die Stunde', e: 'the hour', g: 'f' },
      { t: 'der Tag', e: 'the day', g: 'm' },
      { t: 'die Woche', e: 'the week', g: 'f' },
      { t: 'der Monat', e: 'the month', g: 'm' },
      { t: 'Montag', e: 'Monday' },
      { t: 'Dienstag', e: 'Tuesday' },
      { t: 'Mittwoch', e: 'Wednesday', n: 'Literally "mid-week".' },
      { t: 'Donnerstag', e: 'Thursday' },
      { t: 'Freitag', e: 'Friday' },
      { t: 'Samstag', e: 'Saturday' },
      { t: 'Sonntag', e: 'Sunday' },
      { t: 'der Abend', e: 'the evening', g: 'm' },
      { t: 'die Nacht', e: 'the night', g: 'f' },
      { t: 'früh', e: 'early' },
      { t: 'spät', e: 'late' }
    ],
    sentences: [
      { t: 'Wie spät ist es ?', e: 'what time is it ?', n: 'Literally "how late is it?" — the normal way to ask.' },
      { t: 'Heute ist Montag', e: 'today is Monday' },
      { t: 'Ich arbeite am Morgen', e: 'I work in the morning' },
      { t: 'Bis morgen !', e: 'see you tomorrow !' },
      { t: 'Ich komme zu spät', e: 'I am arriving too late' },
      { t: 'Das Treffen ist am Freitag', e: 'the meeting is on Friday' }
    ] },

  { id: 'de-shop', kind: 'words', title: 'Shopping and money',
    blurb: 'Buying things and asking the price.',
    vocab: [
      { t: 'das Geld', e: 'the money', g: 'n' },
      { t: 'der Preis', e: 'the price', g: 'm' },
      { t: 'die Karte', e: 'the card', g: 'f' },
      { t: 'kaufen', e: 'to buy' },
      { t: 'verkaufen', e: 'to sell' },
      { t: 'bezahlen', e: 'to pay' },
      { t: 'kosten', e: 'to cost' },
      { t: 'die Kleidung', e: 'the clothes', g: 'f' },
      { t: 'das Hemd', e: 'the shirt', g: 'n' },
      { t: 'die Schuhe', e: 'the shoes' },
      { t: 'die Tasche', e: 'the bag', g: 'f' },
      { t: 'das Geschenk', e: 'the gift', g: 'n' },
      { t: 'offen', e: 'open' },
      { t: 'geschlossen', e: 'closed' },
      { t: 'kostenlos', e: 'free of charge' },
      { t: 'andere', e: 'another' },
      { t: 'genug', e: 'enough' },
      { t: 'zu viel', e: 'too much' }
    ],
    sentences: [
      { t: 'Wie viel kostet dieses Hemd ?', e: 'how much does this shirt cost ?' },
      { t: 'Ich möchte mit Karte bezahlen', e: 'I would like to pay by card' },
      { t: 'Das ist zu teuer', e: 'that is too expensive' },
      { t: 'Das Geschäft ist geschlossen', e: 'the shop is closed' },
      { t: 'Ich suche ein Geschenk', e: 'I am looking for a gift' },
      { t: 'Haben Sie eine andere Größe ?', e: 'do you have another size ?' }
    ] },

  { id: 'de-home', kind: 'words', title: 'Home and routine',
    blurb: 'The house, and the shape of a day.',
    vocab: [
      { t: 'die Tür', e: 'the door', g: 'f' },
      { t: 'das Fenster', e: 'the window', g: 'n' },
      { t: 'der Tisch', e: 'the table', g: 'm' },
      { t: 'der Stuhl', e: 'the chair', g: 'm' },
      { t: 'das Bett', e: 'the bed', g: 'n' },
      { t: 'die Küche', e: 'the kitchen', g: 'f' },
      { t: 'das Zimmer', e: 'the room', g: 'n' },
      { t: 'der Schlüssel', e: 'the key', g: 'm' },
      { t: 'das Buch', e: 'the book', g: 'n' },
      { t: 'schlafen', e: 'to sleep' },
      { t: 'aufwachen', e: 'to wake up', n: 'A separable verb: ich wache um sieben auf — the auf goes to the end.' },
      { t: 'waschen', e: 'to wash' },
      { t: 'putzen', e: 'to clean' },
      { t: 'kochen', e: 'to cook' },
      { t: 'öffnen', e: 'to open' },
      { t: 'schließen', e: 'to close' },
      { t: 'suchen', e: 'to look for' },
      { t: 'finden', e: 'to find' }
    ],
    sentences: [
      { t: 'Ich wache um sieben auf', e: 'I wake up at seven' },
      { t: 'Ich koche jeden Tag', e: 'I cook every day' },
      { t: 'Das Buch ist auf dem Tisch', e: 'the book is on the table' },
      { t: 'Kannst du das Fenster öffnen ?', e: 'can you open the window ?' },
      { t: 'Ich finde meinen Schlüssel nicht', e: 'I cannot find my key' },
      { t: 'Ich will mich ausruhen', e: 'I want to rest' }
    ] },

  { id: 'de-travel', kind: 'words', title: 'Travel',
    blurb: 'Getting from one place to another.',
    vocab: [
      { t: 'das Auto', e: 'the car', g: 'n' },
      { t: 'der Zug', e: 'the train', g: 'm' },
      { t: 'das Flugzeug', e: 'the aeroplane', g: 'n', n: 'Literally "flying thing".' },
      { t: 'der Flughafen', e: 'the airport', g: 'm' },
      { t: 'die Fahrkarte', e: 'the ticket', g: 'f' },
      { t: 'der Koffer', e: 'the suitcase', g: 'm' },
      { t: 'die Reise', e: 'the trip', g: 'f' },
      { t: 'der Bahnhof', e: 'the station', g: 'm' },
      { t: 'der Bus', e: 'the bus', g: 'm' },
      { t: 'reisen', e: 'to travel' },
      { t: 'ankommen', e: 'to arrive' },
      { t: 'abfahren', e: 'to depart' },
      { t: 'warten', e: 'to wait' },
      { t: 'verlieren', e: 'to lose' },
      { t: 'laufen', e: 'to walk' },
      { t: 'das Land', e: 'the country', g: 'n' },
      { t: 'der Weg', e: 'the way', g: 'm' },
      { t: 'die Welt', e: 'the world', g: 'f' }
    ],
    sentences: [
      { t: 'Wann fährt der Zug ab ?', e: 'when does the train depart ?' },
      { t: 'Ich habe meinen Koffer verloren', e: 'I have lost my suitcase' },
      { t: 'Ich möchte eine Fahrkarte nach Berlin', e: 'I would like a ticket to Berlin' },
      { t: 'Das Flugzeug kommt um neun an', e: 'the aeroplane arrives at nine' },
      { t: 'Wir reisen mit dem Zug', e: 'we travel by train' },
      { t: 'Wo ist der Bahnhof ?', e: 'where is the station ?' }
    ] },

  { id: 'de-past', kind: 'words', title: 'The past',
    blurb: 'The perfect tense — haben or sein, plus a participle.',
    vocab: [
      { t: 'ich habe gemacht', e: 'I did', n: 'haben + participle. Most verbs work this way.' },
      { t: 'ich habe gegessen', e: 'I ate' },
      { t: 'ich habe gesehen', e: 'I saw' },
      { t: 'ich habe gesagt', e: 'I said' },
      { t: 'ich bin gegangen', e: 'I went', n: 'Verbs of movement take sein, not haben — ich bin gegangen, never ich habe gegangen.' },
      { t: 'ich bin gekommen', e: 'I came' },
      { t: 'ich war', e: 'I was' },
      { t: 'ich hatte', e: 'I had' },
      { t: 'gestern Abend', e: 'last night' },
      { t: 'letzte Woche', e: 'last week' },
      { t: 'vorher', e: 'before' },
      { t: 'danach', e: 'afterwards' },
      { t: 'geboren', e: 'born' },
      { t: 'treffen', e: 'to meet' },
      { t: 'vergessen', e: 'to forget' },
      { t: 'bleiben', e: 'to stay' }
    ],
    sentences: [
      { t: 'Gestern bin ich zum Markt gegangen', e: 'yesterday I went to the market' },
      { t: 'Ich habe im Restaurant gegessen', e: 'I ate at the restaurant' },
      { t: 'Was hast du gemacht ?', e: 'what did you do ?' },
      { t: 'Ich habe nichts gesagt', e: 'I said nothing' },
      { t: 'Ich bin in Kanada geboren', e: 'I was born in Canada' },
      { t: 'Ich habe seinen Namen vergessen', e: 'I have forgotten his name' }
    ] },

  { id: 'de-future', kind: 'words', title: 'Plans and the future',
    blurb: 'What you are going to do.',
    vocab: [
      { t: 'werden', e: 'to become', n: 'Also builds the future: ich werde arbeiten, "I will work".' },
      { t: 'ich werde', e: 'I will' },
      { t: 'müssen', e: 'to have to' },
      { t: 'ich muss', e: 'I must' },
      { t: 'dürfen', e: 'to be allowed to' },
      { t: 'sollen', e: 'should' },
      { t: 'versuchen', e: 'to try' },
      { t: 'anfangen', e: 'to begin' },
      { t: 'beenden', e: 'to finish' },
      { t: 'der Plan', e: 'the plan', g: 'm' },
      { t: 'bald', e: 'soon' },
      { t: 'nächste', e: 'next' },
      { t: 'hoffen', e: 'to hope' },
      { t: 'helfen', e: 'to help' },
      { t: 'lernen', e: 'to learn' },
      { t: 'üben', e: 'to practise' }
    ],
    sentences: [
      { t: 'Ich werde Deutsch lernen', e: 'I will learn German' },
      { t: 'Kannst du mir helfen ?', e: 'can you help me ?' },
      { t: 'Ich muss morgen arbeiten', e: 'I must work tomorrow' },
      { t: 'Wir werden zusammen essen', e: 'we will eat together' },
      { t: 'Nächsten Monat reise ich', e: 'next month I travel' },
      { t: 'Ich hoffe , dich bald zu sehen', e: 'I hope to see you soon' }
    ] },

  { id: 'de-body', kind: 'words', title: 'Health and the body',
    blurb: 'Saying what hurts.',
    vocab: [
      { t: 'der Kopf', e: 'the head', g: 'm' },
      { t: 'das Auge', e: 'the eye', g: 'n' },
      { t: 'der Mund', e: 'the mouth', g: 'm' },
      { t: 'die Hand', e: 'the hand', g: 'f' },
      { t: 'der Fuß', e: 'the foot', g: 'm' },
      { t: 'der Arm', e: 'the arm', g: 'm' },
      { t: 'das Bein', e: 'the leg', g: 'n' },
      { t: 'der Bauch', e: 'the stomach', g: 'm' },
      { t: 'der Rücken', e: 'the back', g: 'm' },
      { t: 'das Herz', e: 'the heart', g: 'n' },
      { t: 'krank', e: 'ill' },
      { t: 'gesund', e: 'healthy' },
      { t: 'die Schmerzen', e: 'the pain' },
      { t: 'die Apotheke', e: 'the pharmacy', g: 'f' },
      { t: 'der Termin', e: 'the appointment', g: 'm' },
      { t: 'wehtun', e: 'to hurt' }
    ],
    sentences: [
      { t: 'Mein Kopf tut weh', e: 'my head hurts' },
      { t: 'Ich bin heute krank', e: 'I am ill today' },
      { t: 'Wie fühlst du dich ?', e: 'how do you feel ?' },
      { t: 'Ich suche eine Apotheke', e: 'I am looking for a pharmacy' },
      { t: 'Ich habe morgen einen Termin', e: 'I have an appointment tomorrow' }
    ] },

  { id: 'de-weather', kind: 'words', title: 'Weather and seasons',
    blurb: 'Small talk, everywhere.',
    vocab: [
      { t: 'das Wetter', e: 'the weather', g: 'n' },
      { t: 'die Sonne', e: 'the sun', g: 'f' },
      { t: 'der Regen', e: 'the rain', g: 'm' },
      { t: 'der Schnee', e: 'the snow', g: 'm' },
      { t: 'der Wind', e: 'the wind', g: 'm' },
      { t: 'die Wolke', e: 'the cloud', g: 'f' },
      { t: 'der Winter', e: 'the winter', g: 'm' },
      { t: 'der Frühling', e: 'the spring', g: 'm' },
      { t: 'der Sommer', e: 'the summer', g: 'm' },
      { t: 'der Herbst', e: 'the autumn', g: 'm' },
      { t: 'regnen', e: 'to rain' },
      { t: 'schneien', e: 'to snow' },
      { t: 'draußen', e: 'outside' },
      { t: 'drinnen', e: 'inside' },
      { t: 'warm', e: 'warm' },
      { t: 'windig', e: 'windy' }
    ],
    sentences: [
      { t: 'Heute ist es sehr kalt', e: 'today it is very cold' },
      { t: 'Es regnet draußen', e: 'it is raining outside' },
      { t: 'Im Winter schneit es viel', e: 'in winter it snows a lot' },
      { t: 'Wie ist das Wetter ?', e: 'what is the weather like ?' },
      { t: 'Ich mag den Frühling', e: 'I like the spring' }
    ] },

  { id: 'de-feel', kind: 'words', title: 'Feelings and opinions',
    blurb: 'Saying what you think.',
    vocab: [
      { t: 'glücklich', e: 'happy' },
      { t: 'traurig', e: 'sad' },
      { t: 'wütend', e: 'angry' },
      { t: 'ruhig', e: 'calm' },
      { t: 'nervös', e: 'nervous' },
      { t: 'denken', e: 'to think' },
      { t: 'ich denke', e: 'I think' },
      { t: 'glauben', e: 'to believe' },
      { t: 'mögen', e: 'to like' },
      { t: 'lieben', e: 'to love' },
      { t: 'hassen', e: 'to hate' },
      { t: 'die Idee', e: 'the idea', g: 'f' },
      { t: 'die Wahrheit', e: 'the truth', g: 'f' },
      { t: 'einverstanden', e: 'in agreement' },
      { t: 'toll', e: 'great' },
      { t: 'langweilig', e: 'boring' }
    ],
    sentences: [
      { t: 'Ich denke , du hast recht', e: 'I think you are right' },
      { t: 'Ich liebe diesen Ort', e: 'I love this place' },
      { t: 'Ich bin sehr glücklich', e: 'I am very happy' },
      { t: 'Ich bin nicht einverstanden', e: 'I do not agree' },
      { t: 'Was denkst du ?', e: 'what do you think ?' },
      { t: 'Der Film war langweilig', e: 'the film was boring' }
    ] },

  { id: 'de-work', kind: 'words', title: 'Work and study',
    blurb: 'What you do, and what you are learning.',
    vocab: [
      { t: 'die Arbeit', e: 'the job', g: 'f' },
      { t: 'die Firma', e: 'the company', g: 'f' },
      { t: 'der Chef', e: 'the boss', g: 'm', p: 'SHEF' },
      { t: 'das Treffen', e: 'the meeting', g: 'n' },
      { t: 'die E-Mail', e: 'the email', g: 'f' },
      { t: 'die Universität', e: 'the university', g: 'f' },
      { t: 'der Unterricht', e: 'the class', g: 'm' },
      { t: 'die Prüfung', e: 'the exam', g: 'f' },
      { t: 'die Frage', e: 'the question', g: 'f' },
      { t: 'die Antwort', e: 'the answer', g: 'f' },
      { t: 'studieren', e: 'to study' },
      { t: 'unterrichten', e: 'to teach' },
      { t: 'das Wort', e: 'the word', g: 'n' },
      { t: 'die Sprache', e: 'the language', g: 'f' },
      { t: 'das Projekt', e: 'the project', g: 'n' },
      { t: 'schwierig', e: 'tricky' }
    ],
    sentences: [
      { t: 'Ich lerne jeden Tag Deutsch', e: 'I learn German every day' },
      { t: 'Ich habe um drei ein Treffen', e: 'I have a meeting at three' },
      { t: 'Was ist deine Arbeit ?', e: 'what is your job ?' },
      { t: 'Ich will eine andere Sprache lernen', e: 'I want to learn another language' },
      { t: 'Ich weiß die Antwort nicht', e: 'I do not know the answer' }
    ] },

  { id: 'de-connect', kind: 'words', title: 'Putting sentences together',
    blurb: 'The small words, and what they do to the verb.',
    vocab: [
      { t: 'und', e: 'and' },
      { t: 'aber', e: 'but' },
      { t: 'oder', e: 'or' },
      { t: 'wenn', e: 'if' },
      { t: 'also', e: 'so', n: 'A false friend: German also means "so" or "therefore", not English "also".' },
      { t: 'dann', e: 'then' },
      { t: 'auch', e: 'also' },
      { t: 'trotzdem', e: 'nevertheless' },
      { t: 'während', e: 'while' },
      { t: 'ohne', e: 'without' },
      { t: 'für', e: 'for' },
      { t: 'bei', e: 'at' },
      { t: 'bis', e: 'until' },
      { t: 'seit', e: 'since' },
      { t: 'etwas', e: 'something' },
      { t: 'nichts', e: 'nothing' }
    ],
    sentences: [
      { t: 'Ich will kommen , aber ich bin müde', e: 'I want to come , but I am tired' },
      { t: 'Wenn es regnet , bleibe ich hier', e: 'if it rains , I stay here', n: 'After a wenn-clause the main verb comes first: bleibe ich, not ich bleibe.' },
      { t: 'Ich lerne Deutsch , weil es mir gefällt', e: 'I learn German because I like it' },
      { t: 'Ich kann ohne Kaffee nicht leben', e: 'I cannot live without coffee' },
      { t: 'Er arbeitet seit zwei Jahren hier', e: 'he has worked here for two years' }
    ] }

  ]
};

Courses.register(GERMAN);
})();
